FROM ubuntu:latest

RUN apt update -y && apt install -y --no-install-recommends zsh vim git
COPY ../.zshrc /root/
COPY ../.ssh/ /root/.ssh/
RUN chmod 600 /root/.ssh/*
RUN chsh -s $(which zsh)

WORKDIR /home