FROM ubuntu:latest

RUN apt update -y && apt upgrade -y
RUN apt install -y zsh vim wget nodejs npm
RUN npm install -g n
RUN n stable
RUN apt purge -y nodejs npm
RUN npm install -g yarn

COPY ../.zshrc /root/
COPY ../.ssh/ /root/.ssh/
RUN chmod 600 /root/.ssh/*
WORKDIR /home
RUN touch /root/.bashrc && echo 'zsh' >> /root/.bashrc
